### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [jet-net/demo-pyhep-2022#1]
Hello @rkansal47, can you kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by rkansal47** [comment]
Done https://github.com/jet-net/demo-pyhep-2022/releases/tag/v1.0, thanks!

**Comment by eduardo-rodrigues** [comment]
All good. I take care of the rest. Thanks.
